### ISSUE TITLE
Elden Souls: Instant cast no SFX or detection event

### ISSUE THREAD

**Issue by ElmoDFGD** [mlthelama/LamasTinyHUD#16]
When using instant cast from top slot w/ Elden Souls option, no SFX are played and no detection event is registered.

https://user-images.githubusercontent.com/118224262/220714004-068bccf4-b7dc-4b3d-8095-894a034e5e60.mp4

Environment:
Device name	Legion
Processor	AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz
Installed RAM	16,0 GB (15,9 GB usable)
OS Win 11
GPU RTX 3070

Modlist
![image](https://user-images.githubusercontent.com/118224262/220714640-51c28940-9947-454b-9b0f-1ef0a05e7e97.png)

**Comment by mlthelama** [comment]
yes, I know of this issue. I did not come around to find a better solution, yet.

**Comment by mlthelama** [comment]
I will probably try to fix both issues with one fix, because it is the same code.

**Comment by mlthelama** [comment]
I did some changes to this code as well, but I have not tested it yet to know if it could be fixed

**Comment by mlthelama** [comment]
fix added to release 1.4.3
