### ISSUE TITLE
Elden Souls: Can only use powers added to top slot

### ISSUE THREAD

**Issue by ElmoDFGD** [mlthelama/LamasTinyHUD#37]
Elden Souls mode. Manually equipped powers from the spells menu that are NOT a part of the configured rotation (i.e. doesn't have a page) cannot be cast. Instead the power/spell currently equipped according to the LamasTinyHUD-rotation is cast. 

https://user-images.githubusercontent.com/118224262/230796027-d8c6d08b-df34-4214-8dcd-35ad15852d96.mp4

Environment:
Device name Legion
Processor AMD Ryzen 7 5800H with Radeon Graphics 3.20 GHz
Installed RAM 16,0 GB (15,9 GB usable)
OS Win 11
GPU RTX 3070

Modlist
![image](https://user-images.githubusercontent.com/118224262/230796074-a48165c8-9cdf-422d-9211-3df2eafbc17e.png)

**Comment by ElmoDFGD** [comment]
Using LamasTinyHUD 1.4.1.

**Comment by mlthelama** [comment]
fix added to release 1.4.3
